// ═══════════════════════════════════════════════════════════════════════════════
// 2027 REYKJAVÍK / AKUREYRI SEASON — SHIP ARRIVALS
// Same row shape as the 2026 SHIPS array in constants.js (port omitted = REY).
// Loaded in month batches from Tristan's schedule; no app view reads this yet —
// access goes through SHIPS_BY_YEAR so a future year toggle is a small change.
// ═══════════════════════════════════════════════════════════════════════════════
import { SHIPS } from "./constants.js";

export const SHIPS_2027 = [
  // ─── APRIL ──────────────────────────────────────────────────────────────────
  { date: "2027-04-08", endDate: "2027-04-09", line: "AIDA Cruises", ship: "AIDAsol", turnaround: false, pax: 2194, status: "other", berth: "Skarfabakki" },
  // ─── MAY ────────────────────────────────────────────────────────────────────
  { date: "2027-05-11", endDate: "2027-05-12", line: "Fred. Olsen Cruise Lines", ship: "Bolette", turnaround: false, pax: 1380, status: "other", berth: "Skarfabakki" },
  { date: "2027-05-13", endDate: "2027-05-15", line: "Ponant", ship: "Le Commandant Charcot", turnaround: true, pax: 250, status: "other", berth: "VÖR Cruise Terminal" },
  { date: "2027-05-19", endDate: null, line: "HX (Hurtigruten Expeditions)", ship: "Fridtjof Nansen", turnaround: true, pax: 530, status: "other", berth: "Miðbakki" },
  { date: "2027-05-20", endDate: "2027-05-21", line: "MSC Cruises", ship: "MSC Preziosa", turnaround: false, pax: 3502, status: "other", berth: "VÖR Cruise Terminal" },
  { date: "2027-05-20", endDate: "2027-05-21", line: "AIDA Cruises", ship: "AIDAsol", turnaround: false, pax: 2194, status: "other", berth: "Skarfabakki" },
  { date: "2027-05-24", endDate: null, line: "Carnival Cruise Line", ship: "Carnival Sunshine", turnaround: false, pax: 3006, status: "other", berth: "Skarfabakki" },
  { date: "2027-05-24", endDate: "2027-05-25", line: "Ponant", ship: "Le Commandant Charcot", turnaround: true, pax: 250, status: "other", berth: "VÖR Cruise Terminal" },
  { date: "2027-05-26", endDate: null, line: "HX (Hurtigruten Expeditions)", ship: "Fridtjof Nansen", turnaround: true, pax: 530, status: "other", berth: "Miðbakki" },
  { date: "2027-05-27", endDate: "2027-05-29", line: "TUI Cruises", ship: "Mein Schiff 3", turnaround: false, pax: 2506, status: "other", berth: "Skarfabakki" },
  { date: "2027-05-29", endDate: null, line: "Holland America Line", ship: "Zuiderdam", turnaround: true, pax: 2272, status: "other", berth: "VÖR Cruise Terminal" },
  { date: "2027-05-31", endDate: null, line: "Swan Hellenic", ship: "SH Vega", turnaround: true, pax: 152, status: "other", berth: "Miðbakki" },
  // ─── JUNE ───────────────────────────────────────────────────────────────────
  { date: "2027-06-01", endDate: "2027-06-02", line: "Explora Journeys", ship: "Explora 4", turnaround: true, pax: 962, status: "other", berth: "VÖR Cruise Terminal" },
  { date: "2027-06-02", endDate: null, line: "HX (Hurtigruten Expeditions)", ship: "Fridtjof Nansen", turnaround: true, pax: 530, status: "other", berth: "Miðbakki" },
  { date: "2027-06-03", endDate: null, line: "Albatros Expeditions", ship: "Ocean Victory", turnaround: true, pax: 199, status: "other", berth: "Miðbakki" },
  { date: "2027-06-05", endDate: null, line: "Peace Boat", ship: "Pacific World", turnaround: false, pax: 1950, status: "other", berth: "VÖR Cruise Terminal" },
  { date: "2027-06-05", endDate: null, line: "Atlas Ocean Voyages", ship: "World Voyager", turnaround: true, pax: 200, status: "other", berth: "Miðbakki" },
  { date: "2027-06-07", endDate: "2027-06-08", line: "Ponant", ship: "Le Commandant Charcot", turnaround: true, pax: 250, status: "other", berth: "VÖR Cruise Terminal" },
  { date: "2027-06-09", endDate: "2027-06-11", line: "Viking", ship: "Viking Vesta", turnaround: true, pax: 998, status: "other", berth: "VÖR Cruise Terminal" },
  { date: "2027-06-09", endDate: null, line: "Regent Seven Seas Cruises", ship: "Seven Seas Splendor", turnaround: false, pax: 746, status: "other", berth: "Skarfabakki" },
  { date: "2027-06-10", endDate: null, line: "Albatros Expeditions", ship: "Ocean Victory", turnaround: true, pax: 199, status: "other", berth: "Miðbakki" },
  { date: "2027-06-11", endDate: "2027-06-13", line: "Viking", ship: "Viking Mars", turnaround: true, pax: 930, status: "other", berth: "Korngarður" },
  { date: "2027-06-11", endDate: "2027-06-12", line: "MSC Cruises", ship: "MSC Preziosa", turnaround: false, pax: 3502, status: "other", berth: "Skarfabakki" },
  { date: "2027-06-12", endDate: null, line: "Atlas Ocean Voyages", ship: "World Voyager", turnaround: true, pax: 200, status: "other", berth: "Miðbakki" },
  { date: "2027-06-13", endDate: null, line: "Holland America Line", ship: "Rotterdam", turnaround: true, pax: 2106, status: "other", berth: "VÖR Cruise Terminal" },
  { date: "2027-06-14", endDate: "2027-06-15", line: "TUI Cruises", ship: "Mein Schiff 2", turnaround: false, pax: 2894, status: "other", berth: "Skarfabakki" },
  { date: "2027-06-15", endDate: null, line: "Princess Cruises", ship: "Regal Princess", turnaround: true, pax: 3560, status: "other", berth: "VÖR Cruise Terminal" },
  { date: "2027-06-16", endDate: "2027-06-17", line: "Norwegian Cruise Line", ship: "Norwegian Prima", turnaround: true, pax: 3195, status: "other", berth: "VÖR Cruise Terminal" },
  { date: "2027-06-18", endDate: "2027-06-19", line: "Ambassador Cruise Line", ship: "Ambience", turnaround: false, pax: 1596, status: "other", berth: "VÖR Cruise Terminal" },
  { date: "2027-06-20", endDate: null, line: "Ambassador Cruise Line", ship: "Ambition", turnaround: false, pax: 1196, status: "other", berth: "VÖR Cruise Terminal" },
  { date: "2027-06-21", endDate: null, line: "AIDA Cruises", ship: "AIDAluna", turnaround: false, pax: 2050, status: "other", berth: "Skarfabakki" },
  { date: "2027-06-22", endDate: null, line: "Hapag-Lloyd Cruises", ship: "Europa", turnaround: false, pax: 408, status: "other", berth: "Skarfabakki" },
  { date: "2027-06-22", endDate: "2027-06-23", line: "Hapag-Lloyd Cruises", ship: "Hanseatic Inspiration", turnaround: true, pax: 230, status: "other", berth: "Miðbakki" },
  { date: "2027-06-25", endDate: null, line: "Viking", ship: "Viking Vela", turnaround: true, pax: 998, status: "other", berth: "VÖR Cruise Terminal" },
  { date: "2027-06-25", endDate: null, line: "Silversea Cruises", ship: "Silver Wind", turnaround: true, pax: 302, status: "other", berth: "Miðbakki" },
  { date: "2027-06-25", endDate: "2027-06-27", line: "TUI Cruises", ship: "Mein Schiff 2", turnaround: false, pax: 2894, status: "other", berth: "Skarfabakki" },
  { date: "2027-06-26", endDate: null, line: "Lindblad Expeditions", ship: "National Geographic Explorer", turnaround: true, pax: 148, status: "other", berth: "Miðbakki" },
  { date: "2027-06-27", endDate: "2027-06-29", line: "Viking", ship: "Viking Sea", turnaround: true, pax: 930, status: "other", berth: "VÖR Cruise Terminal" },
  { date: "2027-06-28", endDate: null, line: "Princess Cruises", ship: "Majestic Princess", turnaround: false, pax: 3560, status: "other", berth: "Skarfabakki" },
  { date: "2027-06-30", endDate: null, line: "Atlas Ocean Voyages", ship: "World Navigator", turnaround: true, pax: 196, status: "other", berth: "Miðbakki" },
  // ─── JULY ───────────────────────────────────────────────────────────────────
  { date: "2027-07-01", endDate: "2027-07-02", line: "AIDA Cruises", ship: "AIDAsol", turnaround: false, pax: 2194, status: "other", berth: "Skarfabakki" },
  { date: "2027-07-02", endDate: "2027-07-03", line: "Celebrity Cruises", ship: "Celebrity Silhouette", turnaround: true, pax: 2886, status: "other", berth: "VÖR Cruise Terminal" },
  { date: "2027-07-03", endDate: null, line: "Lindblad Expeditions", ship: "National Geographic Explorer", turnaround: true, pax: 148, status: "other", berth: "Faxagarður" },
  { date: "2027-07-03", endDate: "2027-07-04", line: "P&O Cruises", ship: "Aurora", turnaround: false, pax: 1868, status: "other", berth: "Skarfabakki" },
  { date: "2027-07-03", endDate: null, line: "Seabourn", ship: "Seabourn Venture", turnaround: true, pax: 250, status: "other", berth: "Miðbakki" },
  { date: "2027-07-04", endDate: null, line: "Oceania Cruises", ship: "Insignia", turnaround: true, pax: 670, status: "other", berth: "Korngarður" },
  { date: "2027-07-04", endDate: null, line: "(unknown)", ship: "SHIP 4", turnaround: false, pax: 2000, status: "other", berth: "VÖR Cruise Terminal" },
  { date: "2027-07-05", endDate: "2027-07-06", line: "Viking", ship: "Viking Sea", turnaround: true, pax: 930, status: "other", berth: "Skarfabakki" },
  { date: "2027-07-05", endDate: null, line: "Princess Cruises", ship: "Sky Princess", turnaround: false, pax: 3660, status: "other", berth: "VÖR Cruise Terminal" },
  { date: "2027-07-06", endDate: "2027-07-07", line: "MSC Cruises", ship: "MSC Preziosa", turnaround: false, pax: 3502, status: "other", berth: "VÖR Cruise Terminal" },
  { date: "2027-07-07", endDate: "2027-07-08", line: "Costa Cruises", ship: "Costa Favolosa", turnaround: false, pax: 3016, status: "other", berth: "Skarfabakki" },
  { date: "2027-07-08", endDate: null, line: "Norwegian Cruise Line", ship: "Norwegian Prima", turnaround: true, pax: 3195, status: "other", berth: "VÖR Cruise Terminal" },
  { date: "2027-07-08", endDate: null, line: "Windstar Cruises", ship: "Star Pride", turnaround: true, pax: 212, status: "other", berth: "Miðbakki" },
  { date: "2027-07-09", endDate: null, line: "Lindblad Expeditions", ship: "National Geographic Endurance", turnaround: true, pax: 170, status: "other", berth: "Miðbakki" },
  { date: "2027-07-09", endDate: "2027-07-10", line: "Celebrity Cruises", ship: "Celebrity Silhouette", turnaround: true, pax: 2886, status: "other", berth: "VÖR Cruise Terminal" },
  { date: "2027-07-09", endDate: null, line: "Fred. Olsen Cruise Lines", ship: "Borealis", turnaround: false, pax: 1404, status: "other", berth: "Skarfabakki" },
  { date: "2027-07-10", endDate: null, line: "Lindblad Expeditions", ship: "National Geographic Explorer", turnaround: true, pax: 148, status: "other", berth: "Miðbakki" },
  { date: "2027-07-10", endDate: null, line: "Ponant", ship: "Le Commandant Charcot", turnaround: true, pax: 250, status: "other", berth: "Skarfabakki" },
  { date: "2027-07-10", endDate: null, line: "Compagnie Française de Croisières", ship: "Renaissance", turnaround: false, pax: 1258, status: "other", berth: "Korngarður" },
  { date: "2027-07-11", endDate: null, line: "Holland America Line", ship: "Zuiderdam", turnaround: true, pax: 2272, status: "other", berth: "VÖR Cruise Terminal" },
  { date: "2027-07-11", endDate: "2027-07-12", line: "P&O Cruises", ship: "Britannia", turnaround: false, pax: 3647, status: "other", berth: "Skarfabakki" },
  { date: "2027-07-12", endDate: "2027-07-13", line: "Viking", ship: "Viking Sea", turnaround: true, pax: 930, status: "other", berth: "VÖR Cruise Terminal" },
  { date: "2027-07-12", endDate: "2027-07-13", line: "AIDA Cruises", ship: "AIDAsol", turnaround: false, pax: 2194, status: "other", berth: "Korngarður" },
  { date: "2027-07-14", endDate: null, line: "Regent Seven Seas Cruises", ship: "Seven Seas Mariner", turnaround: true, pax: 700, status: "other", berth: "VÖR Cruise Terminal" },
  { date: "2027-07-14", endDate: null, line: "Oceania Cruises", ship: "Insignia", turnaround: true, pax: 670, status: "other", berth: "Skarfabakki" },
  { date: "2027-07-15", endDate: null, line: "Windstar Cruises", ship: "Star Pride", turnaround: true, pax: 212, status: "other", berth: "Miðbakki" },
  { date: "2027-07-16", endDate: "2027-07-17", line: "Celebrity Cruises", ship: "Celebrity Silhouette", turnaround: true, pax: 2886, status: "other", berth: "VÖR Cruise Terminal" },
  { date: "2027-07-17", endDate: null, line: "Lindblad Expeditions", ship: "National Geographic Explorer", turnaround: true, pax: 148, status: "other", berth: "Faxagarður" },
  { date: "2027-07-17", endDate: null, line: "Seabourn", ship: "Seabourn Venture", turnaround: true, pax: 250, status: "other", berth: "Miðbakki" },
  { date: "2027-07-17", endDate: null, line: "Fred. Olsen Cruise Lines", ship: "Balmoral", turnaround: false, pax: 1747, status: "other", berth: "Korngarður" },
  { date: "2027-07-18", endDate: null, line: "Lindblad Expeditions", ship: "National Geographic Endurance", turnaround: true, pax: 170, status: "other", berth: "Miðbakki" },
  { date: "2027-07-18", endDate: null, line: "Holland America Line", ship: "Rotterdam", turnaround: true, pax: 2106, status: "other", berth: "VÖR Cruise Terminal" },
  { date: "2027-07-18", endDate: null, line: "Aurora Expeditions", ship: "Douglas Mawson", turnaround: true, pax: 170, status: "other", berth: "Faxagarður" },
  { date: "2027-07-19", endDate: "2027-07-20", line: "Viking", ship: "Viking Sea", turnaround: true, pax: 930, status: "other", berth: "Skarfabakki" },
  { date: "2027-07-19", endDate: null, line: "Silversea Cruises", ship: "Silver Wind", turnaround: true, pax: 302, status: "other", berth: "Miðbakki" },
  { date: "2027-07-20", endDate: null, line: "Albatros Expeditions", ship: "Ocean Victory", turnaround: true, pax: 199, status: "other", berth: "Faxagarður" },
  { date: "2027-07-20", endDate: null, line: "Princess Cruises", ship: "Regal Princess", turnaround: true, pax: 3560, status: "other", berth: "VÖR Cruise Terminal" },
  { date: "2027-07-20", endDate: null, line: "Atlas Ocean Voyages", ship: "World Navigator", turnaround: true, pax: 196, status: "other", berth: "Miðbakki" },
  { date: "2027-07-22", endDate: null, line: "Windstar Cruises", ship: "Star Pride", turnaround: true, pax: 212, status: "other", berth: "Miðbakki" },
  { date: "2027-07-22", endDate: "2027-07-23", line: "Nicko Cruises", ship: "Vasco da Gama", turnaround: false, pax: 1260, status: "other", berth: "Korngarður" },
  { date: "2027-07-23", endDate: "2027-07-24", line: "Viking", ship: "Viking Vela", turnaround: true, pax: 998, status: "other", berth: "Skarfabakki" },
  { date: "2027-07-23", endDate: "2027-07-24", line: "Celebrity Cruises", ship: "Celebrity Silhouette", turnaround: true, pax: 2886, status: "other", berth: "VÖR Cruise Terminal" },
  { date: "2027-07-24", endDate: null, line: "Lindblad Expeditions", ship: "National Geographic Explorer", turnaround: true, pax: 148, status: "other", berth: "Miðbakki" },
  { date: "2027-07-25", endDate: null, line: "AIDA Cruises", ship: "AIDAluna", turnaround: false, pax: 2050, status: "other", berth: "VÖR Cruise Terminal" },
  { date: "2027-07-25", endDate: "2027-07-27", line: "TUI Cruises", ship: "Mein Schiff 3", turnaround: false, pax: 2506, status: "other", berth: "Skarfabakki" },
  { date: "2027-07-26", endDate: "2027-07-27", line: "Viking", ship: "Viking Sea", turnaround: true, pax: 930, status: "other", berth: "VÖR Cruise Terminal" },
  { date: "2027-07-26", endDate: null, line: "Quark Expeditions", ship: "Ultramarine", turnaround: true, pax: 199, status: "other", berth: "Miðbakki" },
  { date: "2027-07-27", endDate: null, line: "Lindblad Expeditions", ship: "National Geographic Endurance", turnaround: true, pax: 170, status: "other", berth: "Miðbakki" },
  { date: "2027-07-27", endDate: null, line: "Aurora Expeditions", ship: "Douglas Mawson", turnaround: true, pax: 170, status: "other", berth: "Faxagarður" },
  { date: "2027-07-28", endDate: null, line: "Albatros Expeditions", ship: "Ocean Albatros", turnaround: true, pax: 186, status: "other", berth: "Miðbakki" },
  { date: "2027-07-28", endDate: "2027-07-29", line: "Norwegian Cruise Line", ship: "Norwegian Prima", turnaround: true, pax: 3195, status: "other", berth: "VÖR Cruise Terminal" },
  { date: "2027-07-28", endDate: "2027-07-29", line: "P&O Cruises", ship: "Arcadia", turnaround: false, pax: 1994, status: "other", berth: "Skarfabakki" },
  { date: "2027-07-29", endDate: null, line: "Windstar Cruises", ship: "Star Pride", turnaround: true, pax: 212, status: "other", berth: "Miðbakki" },
  { date: "2027-07-29", endDate: null, line: "Swan Hellenic", ship: "SH Vega", turnaround: true, pax: 152, status: "other", berth: "Faxagarður" },
  { date: "2027-07-30", endDate: "2027-07-31", line: "Celebrity Cruises", ship: "Celebrity Silhouette", turnaround: true, pax: 2886, status: "other", berth: "VÖR Cruise Terminal" },
  { date: "2027-07-31", endDate: null, line: "Lindblad Expeditions", ship: "National Geographic Explorer", turnaround: true, pax: 148, status: "other", berth: "Faxagarður" },
  { date: "2027-07-31", endDate: null, line: "Silversea Cruises", ship: "Silver Endeavour", turnaround: true, pax: 260, status: "other", berth: "Skarfabakki" },
  { date: "2027-07-31", endDate: null, line: "Plantours Kreuzfahrten", ship: "Hamburg", turnaround: false, pax: 408, status: "other", berth: "Miðbakki" },
];

export const SHIPS_BY_YEAR = {
  2026: SHIPS,
  2027: SHIPS_2027,
};
